project_id = "ofplaocvnlwdnqvlqqka"

[functions.update-member-status]
verify_jwt = true

[functions.create-leader]
verify_jwt = true

[functions.create-pastor]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false